constants:
  MAP: false
  bottlerange:
  - 5
  - 20
  - 35
  - 50
  - 65
  - 80
  - 95
  - 110
  - 125
  - 140
  - 155
  - 170
  - 185
  - 200
  - 215
  - 230
  - 245
  - 260
  - 275
  - 290
  - 305
  - 320
  - 335
  - 350
  - 365
  - 380
  - 395
  - 410
  - 425
  - 440
  - 455
  - 470
  - 485
  epsilon: 0.05
  expressivity: 0
  generations: 250
  iterations: 50
  signaller_type: oldest
  pop_size: 20
  initial_training_rounds: 20
language:
  language_type:
  - 0
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 0
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 0
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 1
  - 2
  - 2
  - 3
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 0
  meanings:
  - '02'
  - '03'
  - '12'
  - '13'
  possible_languages:
  - - &id001
      - '02'
      - aa
    - &id002
      - '03'
      - aa
    - &id003
      - '12'
      - aa
    - &id004
      - '13'
      - aa
  - - *id001
    - *id002
    - *id003
    - &id006
      - '13'
      - ab
  - - *id001
    - *id002
    - *id003
    - &id007
      - '13'
      - ba
  - - *id001
    - *id002
    - *id003
    - &id008
      - '13'
      - bb
  - - *id001
    - *id002
    - &id005
      - '12'
      - ab
    - *id004
  - - *id001
    - *id002
    - *id005
    - *id006
  - - *id001
    - *id002
    - *id005
    - *id007
  - - *id001
    - *id002
    - *id005
    - *id008
  - - *id001
    - *id002
    - &id009
      - '12'
      - ba
    - *id004
  - - *id001
    - *id002
    - *id009
    - *id006
  - - *id001
    - *id002
    - *id009
    - *id007
  - - *id001
    - *id002
    - *id009
    - *id008
  - - *id001
    - *id002
    - &id010
      - '12'
      - bb
    - *id004
  - - *id001
    - *id002
    - *id010
    - *id006
  - - *id001
    - *id002
    - *id010
    - *id007
  - - *id001
    - *id002
    - *id010
    - *id008
  - - *id001
    - &id011
      - '03'
      - ab
    - *id003
    - *id004
  - - *id001
    - *id011
    - *id003
    - *id006
  - - *id001
    - *id011
    - *id003
    - *id007
  - - *id001
    - *id011
    - *id003
    - *id008
  - - *id001
    - *id011
    - *id005
    - *id004
  - - *id001
    - *id011
    - *id005
    - *id006
  - - *id001
    - *id011
    - *id005
    - *id007
  - - *id001
    - *id011
    - *id005
    - *id008
  - - *id001
    - *id011
    - *id009
    - *id004
  - - *id001
    - *id011
    - *id009
    - *id006
  - - *id001
    - *id011
    - *id009
    - *id007
  - - *id001
    - *id011
    - *id009
    - *id008
  - - *id001
    - *id011
    - *id010
    - *id004
  - - *id001
    - *id011
    - *id010
    - *id006
  - - *id001
    - *id011
    - *id010
    - *id007
  - - *id001
    - *id011
    - *id010
    - *id008
  - - *id001
    - &id012
      - '03'
      - ba
    - *id003
    - *id004
  - - *id001
    - *id012
    - *id003
    - *id006
  - - *id001
    - *id012
    - *id003
    - *id007
  - - *id001
    - *id012
    - *id003
    - *id008
  - - *id001
    - *id012
    - *id005
    - *id004
  - - *id001
    - *id012
    - *id005
    - *id006
  - - *id001
    - *id012
    - *id005
    - *id007
  - - *id001
    - *id012
    - *id005
    - *id008
  - - *id001
    - *id012
    - *id009
    - *id004
  - - *id001
    - *id012
    - *id009
    - *id006
  - - *id001
    - *id012
    - *id009
    - *id007
  - - *id001
    - *id012
    - *id009
    - *id008
  - - *id001
    - *id012
    - *id010
    - *id004
  - - *id001
    - *id012
    - *id010
    - *id006
  - - *id001
    - *id012
    - *id010
    - *id007
  - - *id001
    - *id012
    - *id010
    - *id008
  - - *id001
    - &id013
      - '03'
      - bb
    - *id003
    - *id004
  - - *id001
    - *id013
    - *id003
    - *id006
  - - *id001
    - *id013
    - *id003
    - *id007
  - - *id001
    - *id013
    - *id003
    - *id008
  - - *id001
    - *id013
    - *id005
    - *id004
  - - *id001
    - *id013
    - *id005
    - *id006
  - - *id001
    - *id013
    - *id005
    - *id007
  - - *id001
    - *id013
    - *id005
    - *id008
  - - *id001
    - *id013
    - *id009
    - *id004
  - - *id001
    - *id013
    - *id009
    - *id006
  - - *id001
    - *id013
    - *id009
    - *id007
  - - *id001
    - *id013
    - *id009
    - *id008
  - - *id001
    - *id013
    - *id010
    - *id004
  - - *id001
    - *id013
    - *id010
    - *id006
  - - *id001
    - *id013
    - *id010
    - *id007
  - - *id001
    - *id013
    - *id010
    - *id008
  - - &id014
      - '02'
      - ab
    - *id002
    - *id003
    - *id004
  - - *id014
    - *id002
    - *id003
    - *id006
  - - *id014
    - *id002
    - *id003
    - *id007
  - - *id014
    - *id002
    - *id003
    - *id008
  - - *id014
    - *id002
    - *id005
    - *id004
  - - *id014
    - *id002
    - *id005
    - *id006
  - - *id014
    - *id002
    - *id005
    - *id007
  - - *id014
    - *id002
    - *id005
    - *id008
  - - *id014
    - *id002
    - *id009
    - *id004
  - - *id014
    - *id002
    - *id009
    - *id006
  - - *id014
    - *id002
    - *id009
    - *id007
  - - *id014
    - *id002
    - *id009
    - *id008
  - - *id014
    - *id002
    - *id010
    - *id004
  - - *id014
    - *id002
    - *id010
    - *id006
  - - *id014
    - *id002
    - *id010
    - *id007
  - - *id014
    - *id002
    - *id010
    - *id008
  - - *id014
    - *id011
    - *id003
    - *id004
  - - *id014
    - *id011
    - *id003
    - *id006
  - - *id014
    - *id011
    - *id003
    - *id007
  - - *id014
    - *id011
    - *id003
    - *id008
  - - *id014
    - *id011
    - *id005
    - *id004
  - - *id014
    - *id011
    - *id005
    - *id006
  - - *id014
    - *id011
    - *id005
    - *id007
  - - *id014
    - *id011
    - *id005
    - *id008
  - - *id014
    - *id011
    - *id009
    - *id004
  - - *id014
    - *id011
    - *id009
    - *id006
  - - *id014
    - *id011
    - *id009
    - *id007
  - - *id014
    - *id011
    - *id009
    - *id008
  - - *id014
    - *id011
    - *id010
    - *id004
  - - *id014
    - *id011
    - *id010
    - *id006
  - - *id014
    - *id011
    - *id010
    - *id007
  - - *id014
    - *id011
    - *id010
    - *id008
  - - *id014
    - *id012
    - *id003
    - *id004
  - - *id014
    - *id012
    - *id003
    - *id006
  - - *id014
    - *id012
    - *id003
    - *id007
  - - *id014
    - *id012
    - *id003
    - *id008
  - - *id014
    - *id012
    - *id005
    - *id004
  - - *id014
    - *id012
    - *id005
    - *id006
  - - *id014
    - *id012
    - *id005
    - *id007
  - - *id014
    - *id012
    - *id005
    - *id008
  - - *id014
    - *id012
    - *id009
    - *id004
  - - *id014
    - *id012
    - *id009
    - *id006
  - - *id014
    - *id012
    - *id009
    - *id007
  - - *id014
    - *id012
    - *id009
    - *id008
  - - *id014
    - *id012
    - *id010
    - *id004
  - - *id014
    - *id012
    - *id010
    - *id006
  - - *id014
    - *id012
    - *id010
    - *id007
  - - *id014
    - *id012
    - *id010
    - *id008
  - - *id014
    - *id013
    - *id003
    - *id004
  - - *id014
    - *id013
    - *id003
    - *id006
  - - *id014
    - *id013
    - *id003
    - *id007
  - - *id014
    - *id013
    - *id003
    - *id008
  - - *id014
    - *id013
    - *id005
    - *id004
  - - *id014
    - *id013
    - *id005
    - *id006
  - - *id014
    - *id013
    - *id005
    - *id007
  - - *id014
    - *id013
    - *id005
    - *id008
  - - *id014
    - *id013
    - *id009
    - *id004
  - - *id014
    - *id013
    - *id009
    - *id006
  - - *id014
    - *id013
    - *id009
    - *id007
  - - *id014
    - *id013
    - *id009
    - *id008
  - - *id014
    - *id013
    - *id010
    - *id004
  - - *id014
    - *id013
    - *id010
    - *id006
  - - *id014
    - *id013
    - *id010
    - *id007
  - - *id014
    - *id013
    - *id010
    - *id008
  - - &id015
      - '02'
      - ba
    - *id002
    - *id003
    - *id004
  - - *id015
    - *id002
    - *id003
    - *id006
  - - *id015
    - *id002
    - *id003
    - *id007
  - - *id015
    - *id002
    - *id003
    - *id008
  - - *id015
    - *id002
    - *id005
    - *id004
  - - *id015
    - *id002
    - *id005
    - *id006
  - - *id015
    - *id002
    - *id005
    - *id007
  - - *id015
    - *id002
    - *id005
    - *id008
  - - *id015
    - *id002
    - *id009
    - *id004
  - - *id015
    - *id002
    - *id009
    - *id006
  - - *id015
    - *id002
    - *id009
    - *id007
  - - *id015
    - *id002
    - *id009
    - *id008
  - - *id015
    - *id002
    - *id010
    - *id004
  - - *id015
    - *id002
    - *id010
    - *id006
  - - *id015
    - *id002
    - *id010
    - *id007
  - - *id015
    - *id002
    - *id010
    - *id008
  - - *id015
    - *id011
    - *id003
    - *id004
  - - *id015
    - *id011
    - *id003
    - *id006
  - - *id015
    - *id011
    - *id003
    - *id007
  - - *id015
    - *id011
    - *id003
    - *id008
  - - *id015
    - *id011
    - *id005
    - *id004
  - - *id015
    - *id011
    - *id005
    - *id006
  - - *id015
    - *id011
    - *id005
    - *id007
  - - *id015
    - *id011
    - *id005
    - *id008
  - - *id015
    - *id011
    - *id009
    - *id004
  - - *id015
    - *id011
    - *id009
    - *id006
  - - *id015
    - *id011
    - *id009
    - *id007
  - - *id015
    - *id011
    - *id009
    - *id008
  - - *id015
    - *id011
    - *id010
    - *id004
  - - *id015
    - *id011
    - *id010
    - *id006
  - - *id015
    - *id011
    - *id010
    - *id007
  - - *id015
    - *id011
    - *id010
    - *id008
  - - *id015
    - *id012
    - *id003
    - *id004
  - - *id015
    - *id012
    - *id003
    - *id006
  - - *id015
    - *id012
    - *id003
    - *id007
  - - *id015
    - *id012
    - *id003
    - *id008
  - - *id015
    - *id012
    - *id005
    - *id004
  - - *id015
    - *id012
    - *id005
    - *id006
  - - *id015
    - *id012
    - *id005
    - *id007
  - - *id015
    - *id012
    - *id005
    - *id008
  - - *id015
    - *id012
    - *id009
    - *id004
  - - *id015
    - *id012
    - *id009
    - *id006
  - - *id015
    - *id012
    - *id009
    - *id007
  - - *id015
    - *id012
    - *id009
    - *id008
  - - *id015
    - *id012
    - *id010
    - *id004
  - - *id015
    - *id012
    - *id010
    - *id006
  - - *id015
    - *id012
    - *id010
    - *id007
  - - *id015
    - *id012
    - *id010
    - *id008
  - - *id015
    - *id013
    - *id003
    - *id004
  - - *id015
    - *id013
    - *id003
    - *id006
  - - *id015
    - *id013
    - *id003
    - *id007
  - - *id015
    - *id013
    - *id003
    - *id008
  - - *id015
    - *id013
    - *id005
    - *id004
  - - *id015
    - *id013
    - *id005
    - *id006
  - - *id015
    - *id013
    - *id005
    - *id007
  - - *id015
    - *id013
    - *id005
    - *id008
  - - *id015
    - *id013
    - *id009
    - *id004
  - - *id015
    - *id013
    - *id009
    - *id006
  - - *id015
    - *id013
    - *id009
    - *id007
  - - *id015
    - *id013
    - *id009
    - *id008
  - - *id015
    - *id013
    - *id010
    - *id004
  - - *id015
    - *id013
    - *id010
    - *id006
  - - *id015
    - *id013
    - *id010
    - *id007
  - - *id015
    - *id013
    - *id010
    - *id008
  - - &id016
      - '02'
      - bb
    - *id002
    - *id003
    - *id004
  - - *id016
    - *id002
    - *id003
    - *id006
  - - *id016
    - *id002
    - *id003
    - *id007
  - - *id016
    - *id002
    - *id003
    - *id008
  - - *id016
    - *id002
    - *id005
    - *id004
  - - *id016
    - *id002
    - *id005
    - *id006
  - - *id016
    - *id002
    - *id005
    - *id007
  - - *id016
    - *id002
    - *id005
    - *id008
  - - *id016
    - *id002
    - *id009
    - *id004
  - - *id016
    - *id002
    - *id009
    - *id006
  - - *id016
    - *id002
    - *id009
    - *id007
  - - *id016
    - *id002
    - *id009
    - *id008
  - - *id016
    - *id002
    - *id010
    - *id004
  - - *id016
    - *id002
    - *id010
    - *id006
  - - *id016
    - *id002
    - *id010
    - *id007
  - - *id016
    - *id002
    - *id010
    - *id008
  - - *id016
    - *id011
    - *id003
    - *id004
  - - *id016
    - *id011
    - *id003
    - *id006
  - - *id016
    - *id011
    - *id003
    - *id007
  - - *id016
    - *id011
    - *id003
    - *id008
  - - *id016
    - *id011
    - *id005
    - *id004
  - - *id016
    - *id011
    - *id005
    - *id006
  - - *id016
    - *id011
    - *id005
    - *id007
  - - *id016
    - *id011
    - *id005
    - *id008
  - - *id016
    - *id011
    - *id009
    - *id004
  - - *id016
    - *id011
    - *id009
    - *id006
  - - *id016
    - *id011
    - *id009
    - *id007
  - - *id016
    - *id011
    - *id009
    - *id008
  - - *id016
    - *id011
    - *id010
    - *id004
  - - *id016
    - *id011
    - *id010
    - *id006
  - - *id016
    - *id011
    - *id010
    - *id007
  - - *id016
    - *id011
    - *id010
    - *id008
  - - *id016
    - *id012
    - *id003
    - *id004
  - - *id016
    - *id012
    - *id003
    - *id006
  - - *id016
    - *id012
    - *id003
    - *id007
  - - *id016
    - *id012
    - *id003
    - *id008
  - - *id016
    - *id012
    - *id005
    - *id004
  - - *id016
    - *id012
    - *id005
    - *id006
  - - *id016
    - *id012
    - *id005
    - *id007
  - - *id016
    - *id012
    - *id005
    - *id008
  - - *id016
    - *id012
    - *id009
    - *id004
  - - *id016
    - *id012
    - *id009
    - *id006
  - - *id016
    - *id012
    - *id009
    - *id007
  - - *id016
    - *id012
    - *id009
    - *id008
  - - *id016
    - *id012
    - *id010
    - *id004
  - - *id016
    - *id012
    - *id010
    - *id006
  - - *id016
    - *id012
    - *id010
    - *id007
  - - *id016
    - *id012
    - *id010
    - *id008
  - - *id016
    - *id013
    - *id003
    - *id004
  - - *id016
    - *id013
    - *id003
    - *id006
  - - *id016
    - *id013
    - *id003
    - *id007
  - - *id016
    - *id013
    - *id003
    - *id008
  - - *id016
    - *id013
    - *id005
    - *id004
  - - *id016
    - *id013
    - *id005
    - *id006
  - - *id016
    - *id013
    - *id005
    - *id007
  - - *id016
    - *id013
    - *id005
    - *id008
  - - *id016
    - *id013
    - *id009
    - *id004
  - - *id016
    - *id013
    - *id009
    - *id006
  - - *id016
    - *id013
    - *id009
    - *id007
  - - *id016
    - *id013
    - *id009
    - *id008
  - - *id016
    - *id013
    - *id010
    - *id004
  - - *id016
    - *id013
    - *id010
    - *id006
  - - *id016
    - *id013
    - *id010
    - *id007
  - - *id016
    - *id013
    - *id010
    - *id008
  signals:
  - aa
  - ab
  - ba
  - bb
  vocabulary_size: 2
  word_size: 2
plotting_params:
  colors:
  - r
  - g
  - blue
  - orange
  labels:
  - Degenerate
  - Holistic
  - Other
  - Compositional
prior_constants:
  alpha: 1
  bias: []
  prior_type: compressible
